SMS: _string.o dbms.o table.o SMS.o
	g++ _string.o dbms.o table.o SMS.o -o SMS
_string.o: _string.cpp
	g++ -c _string.cpp -o _string.o
dbms.o: dbms.cpp
	g++ -c dbms.cpp -o dbms.o
table.o: table.cpp
	g++ -c table.cpp -o table.o
SMS.o: SMS.cpp
	g++ -c SMS.cpp -o SMS.o
